packages:
  - "apps/*"
  - "packages/**/*"

catalog:
  # Core React
  react: "19.1.0"
  react-dom: "19.1.0"
  "@types/react": "19.2.13"
  "@types/react-dom": "19.2.3"

  # React Native / Expo
  react-native: "0.81.5"
  expo: "54.0.33"
  "@expo/metro-runtime": "6.1.2"
  "@expo/vector-icons": "15.0.3"
  "@react-navigation/native": "7.1.28"
  expo-constants: "18.0.13"
  expo-font: "14.0.11"
  expo-linking: "8.0.11"
  expo-router: "6.0.23"
  expo-status-bar: "3.0.9"
  uniwind: "1.3.1"
  react-native-gesture-handler: "2.28.0"
  react-native-reanimated: "4.1.6"
  react-native-safe-area-context: "5.6.2"
  react-native-screens: "4.16.0"
  react-native-web: "0.21.2"
  react-native-worklets: "0.5.1"

  # Shared utilities
  class-variance-authority: "0.7.1"
  clsx: "2.1.1"
  tailwind-merge: "2.6.1"

  # UI Components
  "@base-ui/react": "1.2.0"
  "@radix-ui/react-slot": "1.1.1"
  lucide-react: "0.469.0"

  # Next.js
  next: "16.1.6"

  # Build tools
  "@babel/core": "7.29.0"
  "@babel/runtime": "7.28.6"
  "@vitejs/plugin-react": "4.7.0"
  babel-plugin-react-compiler: "1.0.0"

  # TypeScript
  typescript: "5.9.3"
  "@types/node": "22.19.9"

  # API
  hono: "4.11.8"
  "@orpc/server": "0.46.0"
  "@orpc/client": "0.46.0"
  "@orpc/react-query": "0.46.0"
  "@tanstack/react-query": "5.90.20"
  zod: "3.25.76"

  # Testing
  vitest: "3.2.4"
  "@playwright/test": "1.58.2"
  "@testing-library/react": "16.3.2"
  "@testing-library/react-native": "13.3.3"
  jsdom: "26.1.0"
  jest: "29.7.0"
  jest-expo: "54.0.17"
  "@types/jest": "29.5.14"

  # Tailwind
  tailwindcss: "4.1.18"
  "@tailwindcss/postcss": "4.1.18"
  postcss: "8.5.6"
