packages:
  - "apps/*"
  - "packages/**/*"

catalog:
  # Core React
  react: "^19.0.0"
  react-dom: "^19.0.0"
  "@types/react": "^19.0.0"
  "@types/react-dom": "^19.0.0"

  # React Native / Expo
  react-native: "0.76.6"
  expo: "~52.0.0"

  # TypeScript
  typescript: "^5.7.3"

  # API
  hono: "^4.6.16"
  "@orpc/server": "^0.46.0"
  "@orpc/client": "^0.46.0"
  "@orpc/react-query": "^0.46.0"
  "@tanstack/react-query": "^5.64.2"
  zod: "^3.24.1"

  # Testing
  vitest: "^3.0.4"
  "@playwright/test": "^1.50.0"

  # Tailwind
  tailwindcss: "^3.4.17"
  postcss: "^8.4.49"
  autoprefixer: "^10.4.20"
