packages:
  - "apps/*"
  - "packages/**/*"

catalog:
  # Core React
  react: "^19.2.0"
  react-dom: "^19.2.0"
  "@types/react": "^19.2.0"
  "@types/react-dom": "^19.2.0"

  # React Native / Expo
  react-native: "0.81.5"
  expo: "~54.0.0"
  "@expo/metro-runtime": "~6.1.2"
  "@expo/vector-icons": "^15.0.3"
  "@react-navigation/native": "^7.1.17"
  expo-constants: "~18.0.13"
  expo-font: "~14.0.11"
  expo-linking: "~8.0.11"
  expo-router: "~6.0.23"
  expo-status-bar: "~3.0.9"
  uniwind: "^1.3.1"
  react-native-gesture-handler: "~2.28.0"
  react-native-reanimated: "~4.1.1"
  react-native-safe-area-context: "~5.6.0"
  react-native-screens: "~4.16.0"
  react-native-web: "~0.21.0"
  react-native-worklets: "0.5.1"

  # Shared utilities
  class-variance-authority: "^0.7.1"
  clsx: "^2.1.1"
  tailwind-merge: "^2.6.0"

  # UI Components
  "@base-ui/react": "^1.2.0"
  "@radix-ui/react-slot": "^1.1.1"
  lucide-react: "^0.469.0"

  # Next.js
  next: "^16.0.0"

  # Build tools
  "@babel/core": "^7.26.0"
  "@babel/runtime": "^7.26.0"
  "@vitejs/plugin-react": "^4.3.4"
  babel-plugin-react-compiler: "^1.0.0"

  # TypeScript
  typescript: "^5.7.3"
  "@types/node": "^22.10.5"

  # API
  hono: "^4.6.16"
  "@orpc/server": "^0.46.0"
  "@orpc/client": "^0.46.0"
  "@orpc/react-query": "^0.46.0"
  "@tanstack/react-query": "^5.64.2"
  zod: "^3.24.1"

  # Testing
  vitest: "^3.0.4"
  "@playwright/test": "^1.50.0"
  "@testing-library/react": "^16.1.0"
  jsdom: "^26.0.0"

  # Tailwind
  tailwindcss: "^4.0.0"
  "@tailwindcss/postcss": "^4.0.0"
  postcss: "^8.4.49"
