packages:
  - "apps/*"
  - "packages/**/*"

catalog:
  # Core React
  react: "19.2.4"
  react-dom: "19.2.4"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.1.0"

  # React Native / Expo
  react-native: "0.84.0"
  expo: "~54.0.0"
  "@expo/metro-runtime": "~6.1.2"
  "@expo/vector-icons": "^15.0.3"
  "@react-navigation/native": "^7.1.17"
  expo-constants: "~18.0.13"
  expo-font: "~14.0.11"
  expo-linking: "~8.0.11"
  expo-router: "~6.0.23"
  expo-status-bar: "~3.0.9"
  uniwind: "^1.3.1"
  react-native-gesture-handler: "~2.30.0"
  react-native-reanimated: "~4.2.1"
  react-native-safe-area-context: "~5.6.0"
  react-native-screens: "~4.23.0"
  react-native-web: "~0.21.0"
  react-native-worklets: "0.7.3"

  # Shared utilities
  class-variance-authority: "^0.7.1"
  clsx: "^2.1.1"
  tailwind-merge: "^3.4.0"

  # UI Components
  "@base-ui/react": "^1.2.0"
  "@radix-ui/react-slot": "^1.2.4"
  lucide-react: "^0.564.0"

  # Next.js
  next: "^16.0.0"

  # Build tools
  "@babel/core": "^7.26.0"
  "@babel/runtime": "^7.26.0"
  "@vitejs/plugin-react": "^5.1.4"
  babel-plugin-react-compiler: "^1.0.0"

  # TypeScript
  typescript: "^5.7.3"
  "@types/node": "^25.2.3"

  # API
  hono: "^4.11.9"
  "@orpc/server": "^1.13.5"
  "@orpc/client": "^1.13.5"
  "@orpc/react-query": "^1.13.5"
  "@tanstack/react-query": "^5.90.21"
  zod: "^4.3.6"

  # Testing
  vitest: "^4.0.18"
  "@playwright/test": "^1.50.0"
  "@testing-library/react": "^16.1.0"
  jsdom: "^28.0.0"

  # Tailwind
  tailwindcss: "^4.1.18"
  "@tailwindcss/postcss": "^4.0.0"
  postcss: "^8.5.6"
